name: Generate GitHub Stats

on:
  workflow_dispatch:


permissions:
  contents: write
  
jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create generated directory
        run: mkdir -p generated

      - name: Generate stats
        run: |
          curl -L \
            "https://github-readme-stats.vercel.app/api?username=thisissoroush&show_icons=true&count_private=true&include_all_commits=true" \
            -o generated/stats.svg

      - name: Commit stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add generated/stats.svg
          git diff --cached --quiet || git commit -m "chore: update GitHub stats"
          git push